
backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Imagem de capa", name: "thumbnail", widget: "image", required: false }
      - { label: "Resumo", name: "summary", widget: "text", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
